#!/usr/bin/env python3
"""
Write apps/studio-worker/.env.scale from Neon + optional R2 S3 credentials.

Usage (secrets via env, not argv):
  set NEON_API_KEY=napi_...
  set CLOUDFLARE_API_TOKEN=cfat_...   # R2-capable account token (S3 keys derived automatically)
  set CF_ACCOUNT_ID=10374f367672f4d19db430601db0926b   # optional
  python scripts/studio-scale/provision-scale-env.py

Optional: R2_ACCESS_KEY_ID + R2_SECRET_ACCESS_KEY from the R2 dashboard instead of CLOUDFLARE_API_TOKEN.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENV_OUT = ROOT / "apps" / "studio-worker" / ".env.scale"
NEON_PROJECT = os.environ.get("NEON_PROJECT_ID", "flat-water-69258108")
ACCOUNT_ID = os.environ.get("CF_ACCOUNT_ID", "10374f367672f4d19db430601db0926b")
BUCKET = os.environ.get("R2_BUCKET", "immersive-studio-packs")


def _r2_s3_from_cloudflare_api_token() -> tuple[str, str]:
    """
    Account/User API tokens with R2 permission work as S3 keys:
    Access Key ID = token id (from verify); Secret = SHA-256 of token value.
    See https://developers.cloudflare.com/r2/api/tokens/
    """
    token = os.environ.get("CLOUDFLARE_API_TOKEN", "").strip()
    if not token:
        return "", ""
    url = f"https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/tokens/verify"
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError:
        return "", ""
    if not data.get("success"):
        return "", ""
    result = data.get("result") or {}
    access_id = str(result.get("id") or "").strip()
    if not access_id:
        return "", ""
    return access_id, hashlib.sha256(token.encode("utf-8")).hexdigest()


def _neon_uri() -> str:
    key = os.environ.get("NEON_API_KEY", "").strip()
    if not key:
        raise SystemExit("NEON_API_KEY is required")
    url = (
        f"https://console.neon.tech/api/v2/projects/{NEON_PROJECT}"
        f"/connection_uri?database_name=neondb&role_name=neondb_owner&pooled=true"
    )
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {key}"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = json.loads(resp.read().decode())
    uri = str(data.get("uri") or "").strip()
    if not uri:
        raise SystemExit("Neon API returned no connection uri")
    return uri


def main() -> int:
    database_url = os.environ.get("DATABASE_URL", "").strip() or _neon_uri()
    r2_id = os.environ.get("R2_ACCESS_KEY_ID", "").strip()
    r2_secret = os.environ.get("R2_SECRET_ACCESS_KEY", "").strip()
    if not (r2_id and r2_secret):
        r2_id, r2_secret = _r2_s3_from_cloudflare_api_token()
    has_r2 = bool(r2_id and r2_secret)

    cors = os.environ.get(
        "STUDIO_CORS_ORIGINS",
        "https://immersivelabs.space,https://www.immersivelabs.space,"
        "http://127.0.0.1:5173,http://localhost:5173",
    )

    lines = [
        "# Generated by scripts/studio-scale/provision-scale-env.py — do not commit",
        f"DATABASE_URL={database_url}",
        "STUDIO_QUEUE_BACKEND=postgres",
        "STUDIO_TENANTS_BACKEND=postgres",
        "STUDIO_EMBEDDED_QUEUE_WORKER=0",
        f"STUDIO_JOB_ARTIFACTS={'r2' if has_r2 else 'local'}",
        f"STUDIO_S3_BUCKET={BUCKET}",
        f"STUDIO_S3_ENDPOINT_URL=https://{ACCOUNT_ID}.r2.cloudflarestorage.com",
        "STUDIO_S3_REGION=auto",
        "STUDIO_S3_KEY_PREFIX=immersive-studio/packs",
        f"AWS_ACCESS_KEY_ID={r2_id}",
        f"AWS_SECRET_ACCESS_KEY={r2_secret}",
        f"STUDIO_CORS_ORIGINS={cors}",
        "STUDIO_COMFY_URL=https://comfy.immersivelabs.space",
        "STUDIO_OLLAMA_URL=http://127.0.0.1:11434",
        "STUDIO_OLLAMA_MODEL=tinyllama",
        "STUDIO_QUEUE_WORKER_ID=local-gpu-1",
        "STUDIO_API_PUBLISH=8787",
    ]
    ENV_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {ENV_OUT}")
    if not has_r2:
        print(
            "R2 S3 keys missing — STUDIO_JOB_ARTIFACTS=local until you set R2_ACCESS_KEY_ID + "
            "R2_SECRET_ACCESS_KEY, or CLOUDFLARE_API_TOKEN with R2 access, and re-run.\n"
            f"Dashboard keys: https://dash.cloudflare.com/{ACCOUNT_ID}/r2/api-tokens"
        )
    else:
        src = "explicit R2_*" if os.environ.get("R2_ACCESS_KEY_ID", "").strip() else "CLOUDFLARE_API_TOKEN"
        print(f"R2 S3 credentials configured ({src}) -> STUDIO_JOB_ARTIFACTS=r2")
    return 0


if __name__ == "__main__":
    sys.exit(main())
